$(document).ready(function(){
    $('.food-slider').slick({
        autoplay:true,
        autoplaySpeed:1500,
        slidesToShow:3,
        slideToScroll:1,
        prevArrow:".prev-btn",
        nextArrow:".next-btn",
        responsive:[
            {
                breakpoint:992,
                settings:{
                    slidesToShow:2,
                }
            },
            {
                breakpoint:768,
                settings:{
                    slidesToShow:1,
                }
            }
        ]
    });
    $('.nav-trigger').click(function(){
        $('.site-content-wrapper').toggleClass('scaled');
    }); 
});


